apiVersion: v1
kind: Service
metadata:
  name: patient-service-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patient-service-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    {{- include "patient-service-db.selectorLabels" . | nindent 4 }}
