apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "patient-service.fullname" . }}
  labels:
    {{- include "patient-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "patient-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "patient-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "patient-service.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z patient-service-db 5432; do echo waiting for db; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: BILLING_SERVICE_ADDRESS
              value: "{{ .Values.env.BILLING_SERVICE_ADDRESS }}"
            - name: BILLING_SERVICE_GRPC_PORT
              value: "{{ .Values.env.BILLING_SERVICE_GRPC_PORT }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.env.SPRING_DATASOURCE_PASSWORD }}"
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.env.SPRING_DATASOURCE_URL }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.env.SPRING_DATASOURCE_USERNAME }}"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "{{ .Values.env.SPRING_JPA_HIBERNATE_DDL_AUTO }}"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.SPRING_KAFKA_BOOTSTRAP_SERVERS }}"
            - name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
              value: "{{ .Values.env.SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL }}"
            - name: SPRING_KAFKA_PROPERTIES_SASL_MECHANISM
              value: "{{ .Values.env.SPRING_KAFKA_PROPERTIES_SASL_MECHANISM }}"
            - name: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
              value: "{{ .Values.env.SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG }}"
            - name: SPRING_SQL_INIT_MODE
              value: "{{ .Values.env.SPRING_SQL_INIT_MODE }}"
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
